### ISSUE TITLE
题外话，关于于IntentUtils能否拓展跳转到省电模式界面

### ISSUE THREAD

**Issue by zhangliangming** [SenhLinsh/Utils-Everywhere#1]
最近用了大神写的IntentUtils跳转到权限设置界面，非常好用。不过，我这边有一个新的问题，就是app在后台运行的时候，因为省电模式，app在后台会断网，我现在想直接跳转到省电界面，设置允许app后台运行。不知这个功能难不难实现？博主有实现这个功能吗？

**Comment by zhangliangming** [comment]
@SenhLinsh 多谢大神先

**Comment by zhangliangming** [comment]
@SenhLinsh 我想请问一下，跳转到权限设置界面，那个intent中的class等信息，你是怎样知道的？能说一下方法吗？我最近要弄跳转到省电模式界面

**Comment by SenhLinsh** [comment]
一开始是看网上的一些解决方案，发现不同的 ROM 可能会有不同的跳转方法。目前大部分是总结了网上的一些参考代码，自己验证没问题了，就拿来用了。不过可以举一反三的，你自己可以试一试
参考：https://www.jianshu.com/p/58c6ca8173c4

**Comment by zhangliangming** [comment]
@SenhLinsh 好的。谢谢
