### ISSUE TITLE
oppo和小米的Android8.1系统已经变了

### ISSUE THREAD

**Issue by 1006750457** [SenhLinsh/Utils-Everywhere#2]
希望能更新一下  我这边找不到相关的手机

**Comment by SenhLinsh** [comment]
@1006750457 不知你说的是辨别自定义 ROM 还是跳转系统权限界面，这两块都已经纳入了更新计划，预计会开发新项目独立解决这两个问题。

**Comment by zhangliangming** [comment]
@1006750457 

` private static String getProperty(String propName) {
        String value = null;
        Object roSecureObj;
        try {
            roSecureObj = Class.forName("android.os.SystemProperties")
                    .getMethod("get", String.class)
                    .invoke(null, propName);
            if (roSecureObj != null) value = (String) roSecureObj;
        } catch (Exception e) {
            value = null;
        } finally {
            return value;
        }
    }`
反射获取rom对应的propNamekey是否有内容来判断，不要读取build.prop文件了

小米8.1
` case MIUI: // 小米
                String rom = getMiuiVersion();
                if ("V6".equals(rom) || "V7".equals(rom)) {
                    intent.setAction("miui.intent.action.APP_PERM_EDITOR");
                    intent.setClassName("com.miui.securitycenter", "com.miui.permcenter.permissions.AppPermissionsEditorActivity");
                    intent.putExtra("extra_pkgname", packageName);
                } else if ("V8".equals(rom) || "V9".equals(rom) || "V10".equals(rom)) {
                    intent.setAction("miui.intent.action.APP_PERM_EDITOR");
                    intent.setClassName("com.miui.securitycenter", "com.miui.permcenter.permissions.PermissionsEditorActivity");
                    intent.putExtra("extra_pkgname", packageName);
                } else {
                    intent = getAppDetailsSettingsIntent(packageName);
                }
                break;`
