### ISSUE TITLE
请问osutils已经没了么？

### ISSUE THREAD

**Issue by zhbzhbzhbz** [SenhLinsh/Utils-Everywhere#4]

**Comment by SenhLinsh** [comment]
因为 OSUtils 不是很通用，且维护起来很难，所以我把它放到 Utils-Everywhere-Ex 了。链接：https://github.com/SenhLinsh/Utils-Everywhere-Ex/blob/master/uee/src/main/java/com/linsh/lshutils/utils/OSUtilsEx.java

**Comment by zhbzhbzhbz** [comment]
> 因为 OSUtils 不是很通用，且维护起来很难，所以我把它放到 Utils-Everywhere-Ex 了。链接：https://github.com/SenhLinsh/Utils-Everywhere-Ex/blob/master/uee/src/main/java/com/linsh/lshutils/utils/OSUtilsEx.java

谢谢您~
